apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2020-03-31T14:54:13.907559
    commit.image.appsody.dev/author: phemankita <phemankita@gmail.com>
    commit.image.appsody.dev/committer: GitHub <noreply@github.com>
    commit.image.appsody.dev/date: Fri Jun 26 13:08:23 2020 +0530
    commit.image.appsody.dev/message: 'Merge pull request #11 from oiricaud/master'
    commit.stack.appsody.dev/author: kilnerm <38245247+kilnerm@users.noreply.github.com>
    commit.stack.appsody.dev/committer: GitHub <noreply@github.com>
    commit.stack.appsody.dev/contextDir: /incubator/java-spring-boot2
    commit.stack.appsody.dev/date: Thu May 14 09:37:35 2020 +0100
    commit.stack.appsody.dev/message: 'Merge pull request #340 from groeges/release-0.9-codewind'
    description: This image is the Kabanero development container for the java-spring-boot2
      stack
    distribution-scope: public
    image.opencontainers.org/created: "2020-06-26T13:14:05+05:30"
    image.opencontainers.org/documentation: https://github.com/ibm-garage-ref-storefront/inventory-ms-spring
    image.opencontainers.org/revision: 211cdcb393d93dcdcd4b4594c81bd58c146a48ef
    image.opencontainers.org/source: https://github.com/ibm-garage-ref-storefront/inventory-ms-spring/tree/master
    image.opencontainers.org/url: https://github.com/ibm-garage-ref-storefront/inventory-ms-spring
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-spring-boot2
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1007.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "408"
    stack.appsody.dev/authors: Erin Schnabel <ebullient>, Ozzy Osborne <bardweller>,
      Richard Trotter <richard-trotter>, Harish Yayi <yharish991>
    stack.appsody.dev/configured: docker.io/kabanero/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-05-19T06:48:21Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/documentation: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2/README.md
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/revision: 104bb146d0d770e30886b845d7fca9311d54ed20
    stack.appsody.dev/source: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2/image
    stack.appsody.dev/tag: docker.io/kabanero/java-spring-boot2:0.3.29
    stack.appsody.dev/title: Spring Boot®
    stack.appsody.dev/url: https://github.com/kabanero-io/collections/tree/master/incubator/java-spring-boot2
    summary: Image for Kabanero java-spring-boot2 development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-408
    vcs-ref: 26f36bfa3e3a04c8c866b250924c1aefc34f01c9
    vcs-type: git
    vendor: Kabanero
    version: 0.3.23
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: inventory-ms-spring
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.29
  name: inventory-ms-spring
  namespace: storefront-dev
spec:
  applicationImage: dev.local/inventory-ms-spring
  createKnativeService: false
  env:
  - name: MYSQL_HOST
    value: inventory-mysql
  - name: MYSQL_PORT
    value: "3306"
  - name: MYSQL_DATABASE
    value: inventorydb
  - name: MYSQL_USER
    value: dbuser
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mysql-password
        name: inventory-mysql
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /micro/actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /micro/actuator/prometheus
    labels:
      k8s-app: inventory-ms-spring
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /micro/actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /micro/actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
